# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call('_Team05Lab06_rcpp_hello_world', PACKAGE = 'Team05Lab06')
}

#' vecSum
#' 
#' This function returns the sum of the elements of a vector
#' @param v A numeric vector
#' @export
vecSum <- function(v) {
    .Call('_Team05Lab06_vecSum', PACKAGE = 'Team05Lab06', v)
}

